[project]
name = "enterprise-it-support-agentic-rag-system"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tajveer", email = "tajveertyagi@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
enterprise-it-support-agentic-rag-system = "enterprise_it_support_agentic_rag_system:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
